name = "RoboPuzzle"
uuid = "b6c37e8e-ad40-11e8-1077-d1cbf6eeb248"
authors = ["scottiealexander <scottiealexander11@gmail.com>"]
version = "0.1.0"

[deps]
Acorn2 = "db1ddef4-ad50-11e8-317c-f1573ad554df"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
